version: '3'

services:

    micro:
        image: micro
        restart: always
        build:
            context: ./api/Micro
            dockerfile: Dockerfile
        networks:
            - backend
        container_name: micro
        volumes:
            - $PWD/api/Micro/src:/usr/local/micro/src

    gateway:
        image: gateway
        restart: always
        build:
            context: ./api/Gateway
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks:
            - backend
        depends_on:
            - micro
        container_name: gateway
        volumes:
            - $PWD/api/Gateway/src:/usr/local/gateway/src

    client:
        image: client
        restart: always
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        container_name: client
        volumes:
            - $PWD/client/src/:/usr/local/client/src/

networks:
    backend:
        driver: bridge
